### ISSUE TITLE
Don't assume the root password is set to root.

### ISSUE THREAD

**Issue by damm** [SimpleFinance/chef-influxdb#42]
All the providers have root/root hardcoded.  Moving the password to attributes (or a resource) and a rescue clause should be able to make this a little more awesome.

**Comment by sge-babrams** [comment]
+1

**Comment by webmat** [comment]
@jakedavis I'd like to start work on a PR to make the root password configurable.

Here's the approach I have in mind. Please let me know if that sounds good, or if you have feedback. 

The providers will look for the password in this order:

1. LWRP attribute, which defaults to nil.
2. In the temporary hash `node.run_state`, at `node.run_state['influxdb_default_root_password']`. If not set, this defaults to nil, being a hash-like structure. The run_state doesn't get saved, so it's safe enough to grab an encrypted databag's content and put it there in a wrapper cookbook.
3. In a node attribute, which defaults to nil as well. Simplifies tests with TestKitchen, or may be good enough for Chef Solo or infras where security is not a high concern.
4. Default to 'root'

The providers would not only accept the password as a parameter, but also the remote endpoint (domain, port). This will make the LWRPs useable to manage the state of hosted InfluxDB.

If I get something like this done, and it's backwards compatible with the current version (defaulting to 'root' password, and 'localhost'), how likely are you to merge this? Do you have any other suggestion?

**Comment by webmat** [comment]
Actually, disregard me. I need to be able to configure more than one influx per environment, so I've decided to start from scratch on a library cookbook. Didn't want to add the complexity of the overridable connection info to your code.

**Comment by damm** [comment]
Yeah that's pretty much what I was thinking is required; a pretty good LWRP here

**Comment by jakedavis** [comment]
Hey @webmat, terribly sorry about being incommunicado here. I'm definitely not against a PR to make the root password configurable. Your call if you think this cookbook is the best spot or not :) sorry again for the late reply.

**Comment by damm** [comment]
Very late reply.
