### ISSUE TITLE
Updated Chef Client

### ISSUE THREAD

**Issue by gadgetmg** [SimpleFinance/chef-influxdb#80]
Is there any reason this cookbook still tests on Chef 11.8.2?

Updating to the latest, 12.5.1, would enable resources to be rewritten in a new way that's much simpler and readable: https://docs.chef.io/custom_resources.html.

I'd be happy to contribute this, but I thought I'd check first to make sure that there's no reason you don't want to upgrade. Maybe even it could constitute a new 4.0 release while maintaining 3.0 for older clients.

**Comment by shortdudey123** [comment]
See https://github.com/SimpleFinance/chef-influxdb/issues/83
